#!/usr/bin/env python3
"""
Bundle the modular app into ONE self-contained HTML file that works from
file:// (double-click, no server, no network except fonts).

    python3 tools/build.py

Writes ./sweaty-dyno.html. The modular version in index.html stays the source
of truth -- rerun this whenever you change js/, css/ or data/.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ['league', 'managers', 'bank', 'minigames', 'drafts', 'trades', 'stats', 'players', 'rules']

# Dependency order: a module must appear after everything it imports.
ORDER = [
    'js/config.js', 'js/supabase.js', 'js/util.js', 'js/db.js', 'js/sleeper.js',
    'js/views/dashboard.js', 'js/views/bank.js', 'js/views/minigames.js',
    'js/views/drafts.js', 'js/views/trades.js', 'js/views/stats.js', 'js/views/rules.js',
    'js/views/empire.js', 'js/views/managers.js', 'js/views/admin.js',
    'js/app.js',
]

IMPORT_RE  = re.compile(r'^\s*import\s+(.+?)\s+from\s+[\'"](.+?)[\'"]\s*;?\s*$', re.M)
EXPORT_DECL = re.compile(r'^\s*export\s+(?=(?:async\s+)?(?:const|let|var|function|class)\b)', re.M)


def key_for(importer: str, spec: str) -> str:
    """Resolve a relative specifier against the importing module's folder."""
    return str((Path(importer).parent / spec).resolve().relative_to(ROOT)).replace('\\', '/')


def exported_names(src: str):
    names = []
    for m in re.finditer(r'^\s*export\s+(?:async\s+)?(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)', src, re.M):
        names.append(m.group(1))
    # `export const a = 1, b = 2;`
    for m in re.finditer(r'^\s*export\s+(?:const|let|var)\s+([^=;\n]+?)\s*=', src, re.M):
        head = m.group(1)
        if ',' in head:
            names += [n.strip() for n in head.split(',') if re.fullmatch(r'[A-Za-z_$][\w$]*', n.strip())]
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n); out.append(n)
    return out


def transform(path: str) -> str:
    src = (ROOT / path).read_text(encoding='utf-8')
    names = exported_names(src)

    def repl(m):
        clause, spec = m.group(1).strip(), m.group(2)
        dep = key_for(path, spec)
        if clause.startswith('*'):                       # import * as NS from '...'
            ns = clause.split(' as ')[1].strip()
            return f'const {ns} = __M["{dep}"];'
        if clause.startswith('{'):                       # import { a, b as c } from '...'
            inner = clause.strip('{} ').strip()
            parts = []
            for p in inner.split(','):
                p = p.strip()
                if not p:
                    continue
                parts.append(p.replace(' as ', ': ') if ' as ' in p else p)
            return 'const { ' + ', '.join(parts) + f' }} = __M["{dep}"];'
        return f'const {clause} = __M["{dep}"].default;'  # default import

    body = IMPORT_RE.sub(repl, src)
    body = EXPORT_DECL.sub('', body)
    ret = '{ ' + ', '.join(names) + ' }' if names else '{}'
    return (f'/* ===== {path} ===== */\n__M["{path}"] = (function () {{\n'
            f'{body}\nreturn {ret};\n}})();\n')


def main():
    css = (ROOT / 'css' / 'style.css').read_text(encoding='utf-8')
    data = {k: json.loads((ROOT / 'data' / f'{k}.json').read_text(encoding='utf-8')) for k in DATA}

    missing = [p for p in ORDER if not (ROOT / p).exists()]
    if missing:
        sys.exit(f'Missing modules: {missing}')

    bundle = '\n'.join(transform(p) for p in ORDER)
    html = (ROOT / 'index.html').read_text(encoding='utf-8')
    head = html.split('<link rel="stylesheet" href="css/style.css">')[0]
    head = head.replace('<link rel="stylesheet" href="css/style.css">', '')

    out = f'''{head}<style>
{css}
</style>
</head>
<body>
<noscript><div style="padding:24px;color:#EAF0F6;font-family:system-ui">
  Sweaty Dyno needs JavaScript to render the league data.</div></noscript>
<script>
/* Single-file build -- generated by tools/build.py. Do not edit by hand;
   edit js/, css/ and data/ then rerun the build. */
window.__SD_DATA = {json.dumps(data, separators=(',', ':'), ensure_ascii=False)};
var __M = {{}};
{bundle}
</script>
</body>
</html>
'''
    dest = ROOT / 'sweaty-dyno.html'
    dest.write_text(out, encoding='utf-8')
    kb = dest.stat().st_size / 1024
    print(f'Built {dest.name}  ({kb:.0f} KB, {len(ORDER)} modules, {len(DATA)} data files)')


if __name__ == '__main__':
    main()
